"""empty message

Revision ID: 688d9426d55f
Revises: 20c01d413050
Create Date: 2021-10-16 03:47:59.997719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688d9426d55f'
down_revision = '20c01d413050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
