"""empty message

Revision ID: ecae1fc7aab9
Revises: 688d9426d55f
Create Date: 2021-10-16 14:07:48.618155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecae1fc7aab9'
down_revision = '688d9426d55f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('up_show_count', sa.Integer(), nullable=True))
    op.drop_column('Artist', 'upcoming_shows_count')
    op.add_column('Venue', sa.Column('up_show_count', sa.Integer(), nullable=True))
    op.drop_column('Venue', 'upcoming_shows_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('upcoming_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'up_show_count')
    op.add_column('Artist', sa.Column('upcoming_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'up_show_count')
    # ### end Alembic commands ###
